### PR TITLE
refactor: fix details table position

### LINKED ISSUE #395: Object details table should be position top-left relative to the parent container, not the window
The object details that slide out when the `Show Details` button is clicked should appear in the top left of the widget container, but currently it is appearing in the top left of the window (see screenshot).

Fix the styling to ensure that the table appears within the parent container.

### PR DESCRIPTION
**Pull request by soshwosh**
Resolves #395 
Resolves #415 

## What this change does
 
Creates a new generic slide-out component, `SlideoutInfoCard` for the `OrbitalDetails` component in the `OrbitalSim` widget. `SlideoutInfoCard` builds off of a `div` instead of a Headless UI `Dialog` like the original `Slideout` component. This allows `OrbitalDetails` to render within the `OrbitalSim` instead of out at the browser window level, which is how the `Dialog` component was designed.

## Things of Note 
The original `Slideout` mixed JS and CSS directly in the component to handle the dynamic translations. It worked well with the `transition` prop provided on the `Dialog` component. To handle the translation directions with a plain `div`, I’m passing dynamic props into the styled component for `SlideoutInfoCard`. As a result, `SlideoutInfoCard`'s `style.ts` looks like it's halfway to JS, but it felt like the cleanest way to mirror the existing Headless UI transition logic while keeping styles externalized. 

I did try to keep the dynamic logic in the component itself, but I was ending up with some long inline styles on my `div`. Since we aren’t using CSS Modules yet, this felt like the best middle ground where I'm leveraging some features of Styled Components while we're still stuck with it. I’m definitely open to feedback here (especially if you have ideas on how to structure this to make the likely future migration to CSS Modules easier).

## Testing

Use Storybook to test in isolation. I configured the slide direction to react to the dropdown in the Storybook console, but changing the `isActive` boolean in the Storybook console won't do anything. The slideout's visibility only responds to the button click.

To test locally, add the OrbitalSim to a page in a local instance of the Investigations Craft API and spin up the client. Ensure the "Show Details" toggle is enabled and that the JSON data for the widget defines content for the table rows.

### Before:
image

### After:
image

### CODE REVIEW

File: packages/epo-react-lib/src/atomic/SlideoutInfoCard/styles.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+export const SlideoutInfoCard = styled.div<{isOpen?: boolean; slideFrom?: Direction;}>`
+  position: absolute;
+
+  transition: transform 0.5s ease-in-out;
+  transform: ${(
+    {isOpen, slideFrom}) => 
+      isOpen ? 'translate(0, 0)' : 
+      slideFrom ? directions[slideFrom] : directions["left"]};
+  
+  opacity: ${props => (props.isOpen ? 1 : 0)};
```
Comment (jeffinnes) [inline packages/epo-react-lib/src/atomic/SlideoutInfoCard/styles.ts:24]: **🔨 issue:** ‏This conditional `opacity` value is causing the `SlideoutInfoCard` to become transparent immediately upon setting `isOpen` to false, so we don't see the "slide back in" animation.

This can be fixed by adding on an `opacity` definition to the `transition`.

File: packages/epo-react-lib/src/atomic/SlideoutInfoCard/styles.ts
Comment (jeffinnes) [inline packages/epo-react-lib/src/atomic/SlideoutInfoCard/styles.ts:1]: **👏 praise:** ‏
> this felt like the best middle ground where I'm leveraging some features of Styled Components while we're still stuck with it. I’m definitely open to feedback here (especially if you have ideas on how to structure this to make the likely future migration to CSS Modules easier).

I think your instincts are good on this. Inlining JS logic seems to be one of the arguments _for_ using Styled Components. This is cleanly implemented and avoids the messy inline styling.

File: packages/epo-react-lib/src/atomic/SlideoutInfoCard/SlideoutInfoCard.stories.tsx [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+};
+export default meta;
+
+const Template: StoryFn<typeof SlideoutInfoCard> = (args) => {
+
+  const [isActive, setIsActive] = useState(args.isOpen || false);
+  const content = "Lorem ipsum dolor sit amet.";
+
+  return (
+    <>
```
Comment (jeffinnes) [inline packages/epo-react-lib/src/atomic/SlideoutInfoCard/SlideoutInfoCard.stories.tsx]: **🎯 suggestion:** ‏I think this could benefit from a wrapping `div` with a minimum height to ensure the animated slides are fully visible.

File: packages/epo-react-lib/src/atomic/SlideoutInfoCard/SlideoutInfoCard.stories.tsx [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+        type: {
+          summary: "top|bottom|left|right",
+        },
+      },
+    },
+  },
+};
+export default meta;
+
+const Template: StoryFn<typeof SlideoutInfoCard> = (args) => {
```
Comment (jeffinnes) [inline packages/epo-react-lib/src/atomic/SlideoutInfoCard/SlideoutInfoCard.stories.tsx:35]: **🎯 suggestion:** ‏I think this could benefit from a wrapping div with a minimum height to ensure the animated slides are fully visible.

**Review by jeffinnes — CHANGES_REQUESTED** [review]

**Review by jeffinnes — APPROVED** [review]
