### PR TITLE
fix: reversed animation control visbility bug

### LINKED ISSUE #396: Fix OrbitalSim animation control visibility bug
**Describe the bug**
When clicking the backward, pause/play, and forward playback control buttons, the animation pauses and the playback controls disappear from view.

**To Reproduce**
1. In Craft, add the Orbital Sim widget to a page in the Investigation.
2. Ensure the "Add Time Controls" button is enabled.
3. In the client, confirm the time controls are visible.
4. Click on either the "Play/Pause", "Backward" or "Forward" buttons.
5. Observe the animation pause, and the animation controls (Pause/Play, Backward, Forward, Reset, and the Speed Slider) disappear.

**Expected behavior**
When clicking any of the playback control buttons, the playback controls should remain in view. Only the "Add Time Controls" toggle in the Orbital Sim Craft block should control whether the playback controls are visible.

The only playback control that should pause the orbital animation is the "Pause" button. Clicking the "Backward" and "Forward" buttons should not cause the animation to pause.

**Additional context**
This bug was introduced in [this ticket](https://github.com/lsst-epo/epo-react-lib/issues/385).

### PR DESCRIPTION
**Pull request by soshwosh**
Resolves #396 

Also includes an addition of a named export for SortableTable, needed for [implementing SortableTable in the client](https://github.com/lsst-epo/investigations-client/issues/397).

To test: 

1. Add an OrbitalSim block in Craft with time controls enabled.
2. Confirm the time controls are visible in the client and work as expected (ex. Clicking "pause" pauses the animation and the controls do not disappear, etc).
3. In Craft, disable the time controls.
4. Confirm the time controls have disappeared from view and that the animation has paused.

### CODE REVIEW

File: packages/epo-widget-lib/src/widgets/SortableTable/index.tsx [hunk 1]
```diff
@@ -1 +1 @@
-export { default as SortableTable } from "./SortableTable";
+export { default, default as SortableTable } from "./SortableTable";
```
Comment (ericdrosas87) [inline packages/epo-widget-lib/src/widgets/SortableTable/index.tsx:1]: note: this change diff will likely go away after the feature branch is rebased with `develop-v3`

**Review by ericdrosas87 — APPROVED** [review]
